language : python
python:
  - "3.6.1"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  coverage run --source=tests/ test
after_success:
  coveralls